brands=[
  {
    "brand_name": "LumaSkin",
    "band_tagline": "Glow Beyond the Surface",
    "brand_description": "A premium skincare brand focused on science-backed, clean beauty solutions for radiant and healthy skin.",
    "product_type": "Skincare",
    "product_description": "Serums, moisturizers, and cleansers made with natural ingredients and dermatologically tested formulas.",
    "price_range": "High-end",
    "target_aundience": "Urban professionals and skincare enthusiasts",
    "age_group": "25-45",
    "location": "Global",
    "tone": "Elegant and trustworthy",
    "style": "Minimalistic and modern",
    "value": "Transparency, quality, sustainability",
    "competitors": ["The Ordinary", "Drunk Elephant", "Kiehl's"],
    "primary_goal": "Build brand trust and increase online sales",
    "content_preference": ["Educational content", "Before-after results", "User testimonials"],
    "platform": ["Instagram", "YouTube", "Website"]
  },
  {
    "brand_name": "UrbanVibe",
    "band_tagline": "Own Your Street",
    "brand_description": "A trendy streetwear brand offering affordable and stylish clothing inspired by youth culture.",
    "product_type": "Clothing",
    "product_description": "Graphic t-shirts, hoodies, and sneakers designed for everyday street fashion.",
    "price_range": "Affordable",
    "target_aundience": "College students and Gen Z",
    "age_group": "16-25",
    "location": "India",
    "tone": "Bold and energetic",
    "style": "Edgy and urban",
    "value": "Self-expression, affordability, trendiness",
    "competitors": ["H&M", "Zara", "Bewakoof"],
    "primary_goal": "Increase social media engagement and brand awareness",
    "content_preference": ["Memes", "Reels", "Influencer collaborations"],
    "platform": ["Instagram", "TikTok"]
  },
  {
    "brand_name": "TaskFlow",
    "band_tagline": "Work Smarter, Not Harder",
    "brand_description": "A SaaS platform that helps teams manage tasks, automate workflows, and boost productivity.",
    "product_type": "Software",
    "product_description": "Task management tools with AI automation, integrations, and team collaboration features.",
    "price_range": "Subscription-based",
    "target_aundience": "Startups and remote teams",
    "age_group": "22-50",
    "location": "Global",
    "tone": "Professional and helpful",
    "style": "Clean and functional",
    "value": "Efficiency, innovation, collaboration",
    "competitors": ["Asana", "Trello", "ClickUp"],
    "primary_goal": "Generate leads and increase free trial signups",
    "content_preference": ["Tutorials", "Case studies", "Product demos"],
    "platform": ["LinkedIn", "Website", "YouTube"]
  },
  {
    "brand_name": "GreenNest",
    "band_tagline": "Sustainable Living Made Simple",
    "brand_description": "An eco-conscious brand offering sustainable home products to reduce environmental impact.",
    "product_type": "Home goods",
    "product_description": "Reusable kitchen items, bamboo products, and biodegradable cleaning supplies.",
    "price_range": "Mid-range",
    "target_aundience": "Environmentally conscious families",
    "age_group": "28-50",
    "location": "Urban areas",
    "tone": "Warm and inspiring",
    "style": "Natural and earthy",
    "value": "Sustainability, responsibility, simplicity",
    "competitors": ["IKEA", "Bare Necessities", "EcoRight"],
    "primary_goal": "Educate consumers and increase repeat purchases",
    "content_preference": ["DIY tips", "Sustainability guides", "Customer stories"],
    "platform": ["Instagram", "Pinterest", "Blog"]
  }
]